### ISSUE TITLE
Did you have hurdles with Tailwind completion? I tried to configure it of `lsp-bridge` with not luck so far.

### ISSUE THREAD

**Issue by artemkovalyov** [merrickluo/lsp-tailwindcss#65]
@merrickluo, when you have time could you mention if there were any major hurdles to get the completion work with Tailwind LSP Server? 
I tried to achieve it for LSP Bridge and it failed miserably: https://github.com/manateelazycat/lsp-bridge/issues/882
You clearly found some secret source to make it work, @merrickluo. KuDos!

**Comment by merrickluo** [comment]
Hi @artemkovalyov thanks for the compliment. There is no "secret source", but the tailwindcss does assume some field in the initial option and settings to be present, you can find all of them in the lsp-tailwindcss implementation. The ultimate way of debugging this is to start the tailwindcss language server in debug mode and see what's going wrong in the logs.

I'll close this since it's not an issue.

**Comment by artemkovalyov** [comment]
Alright, I've thought of debugging it :) Not much comes from the black box testing... Thanks for getting back on this. I'll use your advise. Your implementation is the only one functioning for Emacs at the moment and its helpful.
